# Generated by Django 3.2.12 on 2022-02-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceresult',
            options={'ordering': ('position',)},
        ),
    ]
